### ISSUE TITLE
Error when build Dockerfile

### ISSUE THREAD

**Issue by TovStalin** [ich777/docker-proxy-server#1] opened 2024-11-12 10:58 UTC
When I try to build a Dockerfile (via `docker build . -t proxy_server`) I got the following error:
```plaintext
 => ERROR [builder 4/6] RUN cd /tmp/dumbproxy/ &&   sed -i 's|Basic realm="dumbproxy"|Basic realm="Please authenticate"|' /tmp/dumbproxy/auth.go &  0.3s
------
 > [builder 4/6] RUN cd /tmp/dumbproxy/ &&   sed -i 's|Basic realm="dumbproxy"|Basic realm="Please authenticate"|' /tmp/dumbproxy/auth.go &&   go get &&   go build:
0.235 sed: /tmp/dumbproxy/auth.go: No such file or directory
------
Dockerfile:10
--------------------
   9 |     
  10 | >>> RUN cd /tmp/dumbproxy/ && \
  11 | >>>   sed -i 's|Basic realm="dumbproxy"|Basic realm="Please authenticate"|' /tmp/dumbproxy/auth.go && \
  12 | >>>   go get && \
  13 | >>>   go build
  14 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /tmp/dumbproxy/ &&   sed -i 's|Basic realm=\"dumbproxy\"|Basic realm=\"Please authenticate\"|' /tmp/dumbproxy/auth.go &&   go get &&   go build" did not complete successfully: exit code: 1
```

Looks like this file moved to `auth/basic.go`

**Comment by ich777** [comment] 2024-11-12 11:15
@TovStalin thanks for catching that. Already fixed, please close the issue if the issue is solved for you.

**Closed as completed** 2024-11-16 09:04 UTC
